// Icon exports for Panhaha
// Using Phosphor icons to match MiyZapis design

// Batch 0: Initial icons
export { CalendarIcon } from './CalendarIcon';
export { CalendarDaysIcon } from './CalendarDaysIcon';
export { ClockIcon } from './ClockIcon';
export { PlusIcon } from './PlusIcon';
export { XMarkIcon } from './XMarkIcon';
export { CheckIcon } from './CheckIcon';
export { TrashIcon } from './TrashIcon';
export { PencilIcon } from './PencilIcon';
export { PencilSquareIcon } from './PencilSquareIcon';
export { ChevronLeftIcon } from './ChevronLeftIcon';
export { ChevronRightIcon } from './ChevronRightIcon';
export { ChevronDownIcon } from './ChevronDownIcon';
export { ChevronUpIcon } from './ChevronUpIcon';
export { StarIcon } from './StarIcon';
export { HeartIcon } from './HeartIcon';
export { ChatBubbleLeftIcon } from './ChatBubbleLeftIcon';
export { ChatBubbleLeftEllipsisIcon } from './ChatBubbleLeftEllipsisIcon';

// Batch 1: High Priority Navigation
export { BellIcon } from './BellIcon';
export { EyeIcon } from './EyeIcon';
export { ArrowLeftIcon } from './ArrowLeftIcon';
export { ArrowRightIcon } from './ArrowRightIcon';
export { ArrowTrendingUpIcon } from './ArrowTrendingUpIcon';
export { ArrowTrendingDownIcon } from './ArrowTrendingDownIcon';
export { ArrowPathIcon } from './ArrowPathIcon';
export { ArrowUpIcon } from './ArrowUpIcon';
export { ArrowDownIcon } from './ArrowDownIcon';
export { ArrowDownTrayIcon } from './ArrowDownTrayIcon';
export { ArrowTopRightOnSquareIcon } from './ArrowTopRightOnSquareIcon';
export { HomeIcon } from './HomeIcon';
export { EyeSlashIcon } from './EyeSlashIcon';
export { UserCircleIcon } from './UserCircleIcon';

// Batch 2: Core Layout Icons
export { Bars3Icon } from './Bars3Icon';
export { MagnifyingGlassIcon } from './MagnifyingGlassIcon';
export { MoonIcon } from './MoonIcon';
export { SunIcon } from './SunIcon';
export { Cog6ToothIcon } from './Cog6ToothIcon';
export { CogIcon } from './CogIcon';
export { ArrowRightOnRectangleIcon } from './ArrowRightOnRectangleIcon';
export { UserIcon } from './UserIcon';
export { BellAlertIcon } from './BellAlertIcon';

// Batch 3: Business Feature Icons
export { BriefcaseIcon } from './BriefcaseIcon';
export { CreditCardIcon } from './CreditCardIcon';
export { CurrencyDollarIcon } from './CurrencyDollarIcon';
export { GiftIcon } from './GiftIcon';
export { UsersIcon } from './UsersIcon';
export { UserGroupIcon } from './UserGroupIcon';
export { WalletIcon } from './WalletIcon';
export { ChartBarIcon } from './ChartBarIcon';
export { PresentationChartLineIcon } from './PresentationChartLineIcon';
export { DocumentTextIcon } from './DocumentTextIcon';
export { DocumentCheckIcon } from './DocumentCheckIcon';
export { DocumentArrowDownIcon } from './DocumentArrowDownIcon';
export { ClipboardDocumentListIcon } from './ClipboardDocumentListIcon';
export { ClipboardDocumentCheckIcon } from './ClipboardDocumentCheckIcon';
export { ClipboardDocumentIcon } from './ClipboardDocumentIcon';
export { ShareIcon } from './ShareIcon';
export { LinkIcon } from './LinkIcon';

// Batch 4: Additional Common Icons
export { EnvelopeIcon } from './EnvelopeIcon';
export { CheckCircleIcon } from './CheckCircleIcon';
export { CheckBadgeIcon } from './CheckBadgeIcon';
export { ExclamationTriangleIcon } from './ExclamationTriangleIcon';
export { InformationCircleIcon } from './InformationCircleIcon';
export { PhotoIcon } from './PhotoIcon';
export { CameraIcon } from './CameraIcon';
export { MapPinIcon } from './MapPinIcon';
export { PhoneIcon } from './PhoneIcon';
export { DevicePhoneMobileIcon } from './DevicePhoneMobileIcon';
export { BoltIcon } from './BoltIcon';
export { AdjustmentsHorizontalIcon } from './AdjustmentsHorizontalIcon';
export { FunnelIcon } from './FunnelIcon';
export { BookOpenIcon } from './BookOpenIcon';
export { FireIcon } from './FireIcon';
export { TrophyIcon } from './TrophyIcon';
export { SparklesIcon } from './SparklesIcon';
export { ListBulletIcon } from './ListBulletIcon';
export { Squares2X2Icon } from './Squares2X2Icon';
export { ShieldCheckIcon } from './ShieldCheckIcon';
export { KeyIcon } from './KeyIcon';
export { GlobeAltIcon } from './GlobeAltIcon';
export { AcademicCapIcon } from './AcademicCapIcon';
export { PaperAirplaneIcon } from './PaperAirplaneIcon';
export { PaperClipIcon } from './PaperClipIcon';
export { InboxIcon } from './InboxIcon';
export { ArchiveBoxIcon } from './ArchiveBoxIcon';
export { EllipsisVerticalIcon } from './EllipsisVerticalIcon';
export { CursorArrowRaysIcon } from './CursorArrowRaysIcon';
export { QuestionMarkCircleIcon } from './QuestionMarkCircleIcon';
export { UserPlusIcon } from './UserPlusIcon';
export { IdentificationIcon } from './IdentificationIcon';
export { FlagIcon } from './FlagIcon';
export { XCircleIcon } from './XCircleIcon';
export { NoSymbolIcon } from './NoSymbolIcon';
export { LifebuoyIcon } from './LifebuoyIcon';
export { ChatBubbleLeftRightIcon } from './ChatBubbleLeftRightIcon';
export { WrenchScrewdriverIcon } from './WrenchScrewdriverIcon';
export { BuildingStorefrontIcon } from './BuildingStorefrontIcon';
export { BuildingOfficeIcon } from './BuildingOfficeIcon';
export { LockClosedIcon } from './LockClosedIcon';
