import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { serviceService } from '@/services/service.service';
import PublicSeo from '@/components/common/PublicSeo';
import { ShareButton } from '@/components/common/ShareButton';
import { PageLoader } from '@/components/ui';
import { getAbsoluteImageUrl } from '@/utils/imageUrl';
import { environment } from '@/config/environment';
import { useLanguage } from '@/contexts/LanguageContext';
import { useCurrency } from '@/contexts/CurrencyContext';
import { StarIcon, ClockIcon, MapPinIcon } from '@/components/icons';

/**
 * Public, shareable service page. Renders a beautiful card-style landing with
 * full OG/Twitter meta + a generated branded share image (og:image) and JSON-LD,
 * so a shared link looks great on any platform/messenger and ranks for SEO/GEO/AEO.
 */
const ServicePublicPage: React.FC = () => {
  const { serviceId } = useParams();
  const { t } = useLanguage();
  const { formatPrice } = useCurrency();
  const [service, setService] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const s = await serviceService.getService(serviceId as string);
        if (alive) setService(s);
      } catch {
        if (alive) setNotFound(true);
      } finally {
        if (alive) setLoading(false);
      }
    })();
    return () => { alive = false; };
  }, [serviceId]);

  if (loading) return <PageLoader />;

  if (notFound || !service) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center text-center px-4">
        <p className="text-lg text-gray-600 dark:text-gray-300">{t('service.notFound') || 'Service not found'}</p>
        <Link to="/search" className="text-primary-600 hover:underline mt-3">{t('nav.search') || 'Search'}</Link>
      </div>
    );
  }

  const sp = service.specialist || {};
  const businessName = sp.businessName || `${sp.user?.firstName || ''} ${sp.user?.lastName || ''}`.trim() || 'MiyZapis';
  const images: string[] = Array.isArray(service.images) ? service.images : [];
  const heroImg = images[0] ? getAbsoluteImageUrl(images[0]) : undefined;
  const price = service.price ?? service.basePrice;
  const currency = (service.currency as 'USD' | 'EUR' | 'UAH') || 'UAH';
  const rating = sp.rating != null ? Number(sp.rating) : null;

  const origin = typeof window !== 'undefined' ? window.location.origin : 'https://miyzapis.com';
  const shareUrl = `${origin}/service/${service.id}`;
  // Branded share card generated by the backend (1200×630 PNG).
  const ogImage = `${environment.API_URL}/services/${service.id}/og.png`;
  const metaDesc = (service.description || `${service.name} — ${businessName}`).replace(/\s+/g, ' ').trim().slice(0, 200);

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name: service.name,
    description: metaDesc,
    ...(heroImg ? { image: heroImg } : {}),
    provider: { '@type': 'LocalBusiness', name: businessName, ...(rating != null ? { aggregateRating: { '@type': 'AggregateRating', ratingValue: rating, reviewCount: sp.reviewCount || 1 } } : {}) },
    ...(price != null ? { offers: { '@type': 'Offer', price, priceCurrency: currency, url: shareUrl, availability: 'https://schema.org/InStock' } } : {}),
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <PublicSeo
        title={`${service.name} — ${businessName} | MiyZapis`}
        description={metaDesc}
        image={ogImage}
        url={shareUrl}
        type="website"
        jsonLd={jsonLd}
      />

      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 overflow-hidden shadow-sm">
          {/* Hero */}
          <div className="relative aspect-[16/9] bg-gray-100 dark:bg-gray-800">
            {heroImg ? (
              <img src={heroImg} alt={service.name} className="w-full h-full object-cover" loading="eager" />
            ) : (
              <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-primary-600 to-blue-800">
                <img src="/miyzapis_logo.png" alt="MiyZapis" className="h-16 w-auto opacity-90" />
              </div>
            )}
            {price != null && (
              <span className="absolute top-4 right-4 bg-yellow-400 text-gray-900 font-bold px-3 py-1.5 rounded-xl text-sm shadow">
                {formatPrice(price, currency)}
              </span>
            )}
          </div>

          <div className="p-6">
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">{service.name}</h1>

            <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-2 text-sm text-gray-500 dark:text-gray-400">
              {rating != null && (
                <span className="flex items-center gap-1"><StarIcon className="w-4 h-4 text-amber-400" active />{rating.toFixed(1)}{sp.reviewCount ? ` (${sp.reviewCount})` : ''}</span>
              )}
              {service.duration && <span className="flex items-center gap-1 tabular-nums"><ClockIcon className="w-4 h-4" />{service.duration} {t('common.minutes')}</span>}
              {(sp.city || sp.address) && <span className="flex items-center gap-1"><MapPinIcon className="w-4 h-4" />{sp.city || sp.address}</span>}
            </div>

            {/* Specialist */}
            <Link to={`/specialist/${sp.id}`} className="flex items-center gap-3 mt-4 p-3 rounded-xl bg-gray-50 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
              {sp.user?.avatar ? (
                <img src={getAbsoluteImageUrl(sp.user.avatar)} alt={businessName} className="w-10 h-10 rounded-full object-cover" onError={(e) => { const el = e.currentTarget; el.onerror = null; el.src = '/miyzapis_logo.png'; }} />
              ) : (
                <span className="w-10 h-10 rounded-full bg-primary-100 dark:bg-primary-900/30 text-primary-600 dark:text-primary-300 flex items-center justify-center font-semibold">{businessName.charAt(0)}</span>
              )}
              <div className="min-w-0">
                <p className="text-sm font-semibold text-gray-900 dark:text-white truncate">{businessName}</p>
                <p className="text-xs text-gray-500 dark:text-gray-400">{t('actions.viewProfile') || 'View profile'}</p>
              </div>
            </Link>

            {service.description && (
              <p className="mt-4 text-gray-700 dark:text-gray-300 whitespace-pre-line">{service.description}</p>
            )}

            <div className="flex flex-wrap items-center gap-3 mt-6">
              <Link
                to={`/booking/${service.id}?source=SHARE`}
                className="flex-1 min-w-[140px] whitespace-nowrap bg-primary-600 hover:bg-primary-700 text-white text-center h-11 inline-flex items-center justify-center px-5 rounded-xl font-semibold transition-colors"
              >
                {t('actions.book') || 'Book'}
              </Link>
              <ShareButton url={shareUrl} title={`${service.name} — ${businessName}`} text={metaDesc} variant="button" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ServicePublicPage;
